### ISSUE TITLE
Process does not end after completion

### ISSUE THREAD

**Issue by brettgriffin** [fleet-data/fleet#1]
Reported that the fleet process hangs in terminal after `Completed in 114479 ms`. Pressing CRTL+C does not kill the process.

Environment:

OSX 10.12.4
iTerm 2, and terminal

fleet version 0.0., 0.0.5, 0.0.6.

**Comment by f8k** [comment]
Determined this was due to an older version of Docker. This is confirmed to have been resolved in `17.09.0-ce-mac33`
