### ISSUE TITLE
TaskStateHelper() should check config.state and window.beginDate

### ISSUE THREAD

**Issue by brettgriffin** [fleet-data/fleet#14]
TaskStateHelper() should also check config.state and window.beginDate when attempting to parse state.

The order of priority should go:
state.json
config.json `state` property
config.json `window.beginDate`

**Comment by jre247** [comment]
@brettgriffin can you clarify why we need to be checking window.beginDate when parsing state? Isn't window.beginDate separate from state, since that's defined on a config?
